name: Deploy Static Landing Page

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**' # Only trigger when files inside your docs folder change

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Setup GitHub Pages Platform Environment
        uses: actions/configure-pages@v4

      - name: Upload Website Artifacts Only
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs' # Tells GitHub to ONLY serve your clean docs folder!

      - name: Deploy to GitHub Pages Natively
        id: deployment
        uses: actions/deploy-pages@v4
